version: 2.1

executors:
  node:
    docker:
      - image: cimg/node:14.17.6
      - image: trufflesuite/ganache-cli
        # environment:
        #   FOOD: $BAR
    resource_class: medium

references:
  # Paths
  default_workspace: &default_workspace ~/beprojs-repo
  # Cache keys
  node_cache_key: &node_cache_key node-v1-{{ checksum "package.json" }}-{{ arch }}
  # Branch filters
  feature_filter: &feature_filter
    branches:
      ignore:
        - master

commands:
  prepare_code:
    steps:
      - checkout:
          path: *default_workspace
      - restore_cache:
          key: *node_cache_key
      - run:
          name: install truffle@5.1.7 globally
          command: sudo npm install -g --unsafe-perm=true truffle@5.1.7
      - save_cache:
          key: *node_cache_key
          paths:
            - node_modules
jobs:
  tests:
    working_directory: *default_workspace
    executor: node
    steps:
      - prepare_code
      - run: mkdir ~/reports

workflows:
  code-checks:
    jobs:
      - tests
