name: integration-tests

on:
  push:
    branches:
      - 2.0.0-alpha.0
      - 2.0.0-alpha.1
  pull_request:
    branches:
    - master
    - 2.0.0-alpha.0
    - 2.0.0-alpha.1

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.17.0]
    steps:
      - uses: actions/checkout@v1
      - name: Install Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: npm install
        run: npm install

      - name: Lint solution
        run: npm run lint

      - name: Build solution
        run: npm run build

      - name: Start ganache and test integration
        run: npm run test-ci
        env:
          CI: true
